name: cicd-ec2

on:
  push:
    branches:
      - main

jobs:
  build_image_deploy:
    runs-on: ubuntu-latest  # Fix: Changed 'runs on' to 'runs-on'
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Fix: Corrected secret variable name
          password: ${{ secrets.DOCKER_PASSWORD }}  # Fix: Used correct syntax for secret
          registry: docker.io

      - name: Build Docker image
        run: docker build -t kartik .

      - name: Push image to DockerHub
        run: |
          docker tag kartik:latest kartikeya1112/latest-image:latest
          docker push kartikeya1112/latest-image:latest

      - name: Deploy to EC2 instance
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}  # Fix: Corrected secret syntax
          SSH_USER: ${{ secrets.SSH_USER }}    # Fix: Used consistent naming
          SSH_IP: ${{ secrets.SSH_IP }}

        run: |
          echo "$SSH_KEY" > centos-key.pem
          chmod 600 centos-key.pem

          ssh -o StrictHostKeyChecking=no -i centos-key.pem $SSH_USER@$SSH_IP << 'EOF'
            sudo apt update
            sudo apt upgrade -y
            sudo apt install docker.io -y
            sudo systemctl enable docker
            sudo systemctl start docker
            sudo docker stop kartik || true
            sudo docker rm kartik || true
            sudo docker pull kartikeya1112/latest-image:latest
            sudo docker run --name=kartik -p 80:5000 -d kartikeya1112/latest-image:latest
          EOF
